description: Proposing a novel joint motion prediction architecture that performs factorized decoding over a learned interaction DAG. Authors: <a href="https://www.linkedin.com/in/rluke22/">Luke Rowe</a>, <a href="https://www.linkedin.com/in/ethiermartin/">Martin Ethier</a>, <a href="https://www.linkedin.com/in/henry-dykhne-ai">Eli-Henry Dykhne</a>, <a href="https://uwaterloo.ca/electrical-computer-engineering/profile/k2czarne">Krzysztof Czarnecki</a>
theme: jekyll-theme-cayman
links:
  arxiv: https://arxiv.org/abs/2211.16197
  code: https://github.com/RLuke22/FJMP
